### ISSUE TITLE
Make engine suitable to run over PGA

### ISSUE THREAD

**Issue by smola** [src-d/okrs#17]
**Parent objective:**  #11
**Progress:** 100%

- [x] [P0] Fix the reported errors and do not crash
- [x] [P1] Report errors with meaning information for tracing the root causes

**Comment by ajnavarro** [comment]
@smola we cannot go deeper on `Improve performance of engine over PGA` before having more metrics/tracing info. To know how far we should go improving performance, we should add some number to this OKR, like expected percentage of performance improvement.

**Comment by ajnavarro** [comment]
The latest engine versions have much better error reports and we fix all the execution errors that appeared.
