### ISSUE TITLE
Define a format that can store UAST in a space-efficient way

### ISSUE THREAD

**Issue by dennwc** [src-d/okrs#25]
**Parent objective:**  #18
**Progress:** 15%

- [ ] [P0] Get current UAST format stats for PGA in comparison with source file sizes.
- [ ] [P0] Try different approaches for storing UAST (binary, string tables, etc).

**Comment by marnovo** [comment]
[OKRs Review] too detailed for OKRs, more related to technical implementation. Discarded.
