### ISSUE TITLE
Optimize borges to keep up with all repository updates within 30 days

### ISSUE THREAD

**Issue by ajnavarro** [src-d/okrs#27]
**Parent objective:**  #15  
**Progress:** 0/5

- [ ] [P0] improve downloading of new repos by 50%
- [ ] [P1] improve update rooted repositories by 50%
- [ ] [P1] increase job throghtput by 30%
- [ ] [P2] decrease timeout errors by 30%
- [ ] [P2] decrease pod restarts by 50%

**Comment by ajnavarro** [comment]
@smola can you take a look?

**Comment by bzz** [comment]
Sorry for butting in, but to be able to do this and verify that it's archived, may be one more item needs to be added - to measure all those numbers and publish them i.e here first.

That way, it would be very easy to run same tests in 3 months, and post the numbers here.
