### ISSUE TITLE
Cover top 10 languages from the most used list on StackOverflow's developer survey

### ISSUE THREAD

**Issue by juanjux** [src-d/okrs#29]
**Parent objective:**  #2
**Progress:** 0/4

- [ ] [P1] C# driver.
- [ ] [P1] Typescript driver.
- [ ] [P1] C/C++ driver.
- [ ] [P2] Swift driver.

**Comment by marnovo** [comment]
[OKRs Review] Discarded, will focus on developing the abstractions and tooling on LA.
