### ISSUE TITLE
Having a more diverse funnel in terms of gender and race

### ISSUE THREAD

**Issue by tsolakoua** [src-d/okrs#36]
**Parent objective:**  #4 
**Progress:** 2/3

- [ ] [P1] Identify and solve 2 potential bottlenecks
- [x] [P1] Developer community promotion via social media
- [x] [P2] Getting in touch with existing communities (eg. women developer communities)

**Comment by bzz** [comment]
> and want more women and non-white people in our team

Gender might be [not binary](https://en.m.wikipedia.org/wiki/Gender_systems) so we have to be very careful with a wording on this subject, especially on Twitter.

**Comment by jorgeschnura** [comment]
I think the tweets is a patch, it doesn't solve the underlying issue. We should dive deep into the problem to understand how we can organically attract more women. But both things are not mutually exclusive

**Comment by tsolakoua** [comment]
Yes, that's true @jorgeschnura. From a previous discussion I had with @eiso we said that the main bottleneck is the fact that our roles are very specific and by default don't have a big number of people or the diversity we are looking for. We don't offer roles for "typical" web or frontend developer profiles that there are so many people out there. In my opinion, the more specific people we are looking for, the harder is to build a diverse team. On the other hand, the more specific people we are looking for, the more close we are moving I guess to achieve company-wide goals. @eiso proposed that we could focus on ML as it's a more diverse community compared to the other ones.

**Comment by tsolakoua** [comment]
- 2 female hires in ML team.
- The developer community has approached and brought women candidates in the process. 
- Talent has contacted tech organizations that could help us be more diverse, and already had interviews and feedback from a few of them - see [here](https://github.com/src-d/backlog/issues/1268). 
- Also, joined Women Who Go on their Slack. 
- Our guide is written in a way that doesn't explicitly mention genders (instead, using they).
- About the ```Identify and solve 2 potential bottlenecks``` the main bottleneck identified is: our stack and level of people we are looking for (either senior, or junior but very smart) is not easy to find. For example, there are a lot of frontend, mobile developers out there, but not so many hardcore Go developers.
