### ISSUE TITLE
Collect native AST structures for supported drivers

### ISSUE THREAD

**Issue by dennwc** [src-d/okrs#37]
**Parent objective:**  #21
**Progress:** 6/6

- [x] Go (https://github.com/bblfsh/go-driver/pull/11)
- [x] Java (https://github.com/bblfsh/java-driver/pull/66)
- [x] JavaScript (https://github.com/bblfsh/javascript-driver/pull/15)
- [x] PHP (https://github.com/bblfsh/php-driver/pull/12)
- [x] Python (https://github.com/bblfsh/python-driver/pull/146)
- [x] Ruby (https://github.com/bblfsh/ruby-driver/pull/16)

**Comment by bzz** [comment]
> Progress: 6/6

🥇🥇🥇🥇

**Comment by marnovo** [comment]
[OKRs Review] Since it's done + overly detailed for the OKRs, discarding.
