### ISSUE TITLE
Successfully implement best practices for being a remote company

### ISSUE THREAD

**Issue by gomesfernanda** [src-d/okrs#40]
**Parent objective:** #4
**Progress:** 0%

- [ ] [P0] Create a study on employees sentiment

**Comment by gomesfernanda** [comment]
Q2 status: subtasks were completed, but the key result itself not. Moving this to Q3.

**Comment by marnovo** [comment]
[P0] Create a study on employees sentiment -> Partially done: research/feedback/draft done, policy draft done, actual survey not ready
