### ISSUE TITLE
Build gitbase playground

### ISSUE THREAD

**Issue by bzz** [src-d/okrs#51]
**Parent objective:**  #8
**Progress:** 0%

- [x] [P0] Build web application that allows users to interact with gitbase
- [x] [P0] Run gitbase playground locally (with 1 command, for 1 user)
- [x] [P1] Create new interactive visualization of UAST (and apply to both playgrounds)

**Comment by marnovo** [comment]
[OKRs Review]

Moved to parent: - [ ] [P0] Deploy gitbase playground on src-d infrastructure (>1 concurrent user)

Added: - [ ] [P0] Build web application that allows users to interact with gitbase

**Comment by bzz** [comment]
2nd iteration of [design document](https://docs.google.com/document/d/1mjFWDVtkGO9SQ2az9j1l13kcKfLYX-DQT-QHcfCnxpQ/edit#), covering these KRs is available now.

**Comment by bzz** [comment]
Development work is being tracked under https://github.com/src-d/gitbase-playground/milestones

**Comment by carlosms** [comment]
By End of 2018Q2, setting as done:
- [P0] Build web application that allows users to interact with gitbase
  - We released https://github.com/src-d/gitbase-playground covering all the functionality of the design doc. There are minor things we will keep doing, like docs, testing, bugfixing...
-  [P0] Run gitbase playground locally (with 1 command, for 1 user)
   - Gitbase Playground (and its dependencies) can be run locally very easily with docker-compose
- [P1] Create new interactive visualization of UAST (and apply to both playgrounds)
  - Common library released as https://github.com/bblfsh/uast-viewer and integrated in Gitbase Playground and Babelfish Dashboard.
