### ISSUE TITLE
Research: run Gemini on some repos, generate PR-level report

### ISSUE THREAD

**Issue by bzz** [src-d/okrs#53]
**Parent objective:**  #9
**Progress:** 0%

This is needed in order to determine the usefulness of Gemini's output, as PR-level application.

- [ ] [P0] A DB \w Gemini hashes over some N hand-picked popular repos
- [ ] [P0] A Report on file similarity, for each PR in those repos

**Comment by marnovo** [comment]
[OKRs Review] Discarded, this will be part of the product part of the code review app.
