### ISSUE TITLE
Launch Gemini application: file-level similarity

### ISSUE THREAD

**Issue by bzz** [src-d/okrs#54]
**Parent objective:**  #9
**Progress:** 0%

- [x] [P0] Formally launch Gemini as a standalone application of our stack
- [x] [P0] Run on a single machine, for small number of repositories
- [ ] [P1] Run on Apache Spark cluster, for full PGA
   * [x] Run on Apache Spark cluster, for 1/250th of PGA https://github.com/src-d/gemini/issues/42#issuecomment-400737786
- [ ] [P2] Run on Apache Spark cluster, for full world dataset

**Comment by marnovo** [comment]
[OKRs Review]

Removed:

> Another idea: align \w DR KRs on Engine perf #17 in form of `K% overhead on top of Engine`

> Run on Apache Spark cluster, for full dataset

> Finish work, that has been started 2018Q1 and is covered in [DesignDoc](https://docs.google.com/document/d/1cInzLuz-qygwrTvddGIbzBnzF4nnsAuk_24a6Nhff0k/edit#heading=h.a0vttzyxt24g)

**Comment by bzz** [comment]
Gemini as of [v 0.0.3](https://github.com/src-d/gemini/releases/tag/v0.0.3) has all the necessary features for the release.

Few usability improvements are pending, before cutting actual v0.1. Initial work on running it over PGA has been started at pipeline cluster.

**Comment by bzz** [comment]
End of 2018Q2:
 - [v0.1.0](https://github.com/src-d/gemini/releases/tag/v0.1.0) released, implementing file-level similarity
 - added intermediate results on PGA run to the description
