### ISSUE TITLE
Tune the process with what we learned from these interviews

### ISSUE THREAD

**Issue by gomesfernanda** [src-d/okrs#55]
**Parent objective:**  #33  
**Progress:** 0%

- [ ] [P0] Create research on candidates' sentiment towards on-site and remote interviews

**Comment by gomesfernanda** [comment]
Q2 status: subtasks were completed, but the key result itself not. Moving this to Q3.

**Comment by marnovo** [comment]
[P0] Create research on candidates' sentiment towards on-site and remote interviews -> Research and draft done, need to create actual survey, formal survey policy, and send to candidates
