### ISSUE TITLE
Finalize identifier embeddings

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/okrs#63]
**Parent objective:**  #42 
**Progress:** 0%

Relates to https://github.com/src-d/feature-idea/issues/3

- [ ] [P0] Train the production model with source code identifier embeddings from PGA

**Comment by vmarkovtsev** [comment]
The training code is written and tested. We hit the massive problems with data processing and extraction from the PGA (the infamous Spark and engine instability + lack of k8s experience). Currently finishing to extract identifiers from the PGA. The further steps - generating the model and uploading to Modelforge are done and tested. We also studied a few reference models to compare. @zurk You should have some comparative numbers?

**Comment by zurk** [comment]
yes, just report intermediate results in a corresponding issue: https://github.com/src-d/backlog/issues/1249#issuecomment-401852475
