### ISSUE TITLE
Deliver structured user research

### ISSUE THREAD

**Issue by marnovo** [src-d/okrs#7]
**Parent objective:**  #6 
**Progress:** 0%

- [ ] [P0] Define and describe the key use case segments
- [ ] [P0] Map formally the personas for our products
- [x] [P1] Conduct 15 user research interviews
- [ ] [P1] Conduct quantitative research over the Slack community

**Comment by ricardobaeta** [comment]
Hi there! [Here's the planning](https://docs.google.com/document/d/1lU_-umw1nS8oPMCZbXluAqJN3B5qbsjC_SLZR-msZdE/edit#heading=h.iou7axd1bxwk).

**Comment by ricardobaeta** [comment]
@marnovo We can include in this okr's issue the Gitbase Playground Research Report 1

**Comment by marnovo** [comment]
[P0] Define and describe the key use case segments -> For gitbase playground yes, other products not
[P0] Map formally the personas for our products -> Partially, but formally only for CAT
[P1] Conduct 15 user research interviews -> Mostly: 8 on gitbase/playground, 4 on the landing
[P1] Conduct quantitative research over the Slack community -> Only covered geography/messaging stats, not profiles
